"""Corrección de CORS y mejoras en app.py

Revision ID: 137686b29318
Revises: 5ee2f734b69e
Create Date: 2025-02-28 22:24:21.569659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137686b29318'
down_revision = '5ee2f734b69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_property_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_status'))
        batch_op.drop_index(batch_op.f('ix_property_price'))
        batch_op.drop_index(batch_op.f('ix_property_location'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('images',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
