"""Corrigiendo errores de NULL en property_type y user_id

Revision ID: caecebddfc51
Revises: 7dce9aabc2f5
Create Date: 2025-03-01 13:43:27.783130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caecebddfc51'
down_revision = '7dce9aabc2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_property_location')
        batch_op.drop_index('ix_property_price')
        batch_op.drop_index('ix_property_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_index('ix_property_status', ['status'], unique=False)
        batch_op.create_index('ix_property_price', ['price'], unique=False)
        batch_op.create_index('ix_property_location', ['location'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
