"""Añadir filtros avanzados de Idealista y Zillow

Revision ID: f4ca1738cdb2
Revises: caecebddfc51
Create Date: 2025-03-01 23:52:14.416945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ca1738cdb2'
down_revision = 'caecebddfc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surface', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lot_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_built', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_floors', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_basement', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_garage', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_pool', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_elevator', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_accessible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_luxury', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_bank_owned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_virtual_tour', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('published_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('published_date')
        batch_op.drop_column('has_virtual_tour')
        batch_op.drop_column('is_bank_owned')
        batch_op.drop_column('is_luxury')
        batch_op.drop_column('is_accessible')
        batch_op.drop_column('has_elevator')
        batch_op.drop_column('has_pool')
        batch_op.drop_column('has_garage')
        batch_op.drop_column('has_basement')
        batch_op.drop_column('num_floors')
        batch_op.drop_column('year_built')
        batch_op.drop_column('lot_size')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('bedrooms')
        batch_op.drop_column('surface')

    # ### end Alembic commands ###
